## CONFIGURACIÓN DE LA BASE DE DATOS MARIA DB
spring.datasource.url=jdbc:mariadb://localhost:3306/minimarket_db?createDatabaseIfNotExist=true
spring.datasource.username=${MARIA_DB_USERNAME}
spring.datasource.password=${MARIA_DB_PASSWORD}}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

## CONFIGURACIÓN DE JPA / HIBERNATE (development)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

## VARIABLES JWT
jwt.secret=${SECRET_TOKEN_JWT}
jwt.expiration=${JWT_EXPIRATION}